config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # Routes for Google authentication Login and Register
  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/about', to: 'about#index'

  resources :users, only: [:update, :edit]

  # Routes for a users extra information to be uploaded
  get '/extra_user_info_index/:id', to: 'extra_info#index', as: :extra_info
  get '/edit_extra_user_info/:id', to: 'extra_info#edit', as: :edit_extra_info
  put '/extra_user_info_edit/:id', to: 'extra_info#update', as: :update_info


  # User Profile Paths
  get '/profile', to: 'users#show', as: :profile
  get '/profile/edit', to: 'users#edit'
  patch '/profile/edit', to: 'users#update'
  namespace :profile do
    resources :contacts, only: [:new]
  end

  # Contact paths (also check contact paths namespaced in profile)
  resources :contacts, only: [:create]
  get '/contact_login', to: 'contact_login#edit'
  patch '/contact_login', to: 'contact_login#update'

  # GROUP do we want to namespace this?
  get '/dashboard', to: 'dashboard#index'

  # notification paths
  get '/notification', to: 'notification#message_sender'

  get '/report/:id', to: 'report#show', as: :report

  # dead_man_switch paths
  resources :dead_man_switch, only: [:create, :update, :destroy]

  #funeral arrangement path
  resources :users do
    resources :funerals, only: [:create, :new, :edit, :update]
  end

  # match '*path', to: 'application#four_oh_four', via: :all

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_reguser

  def index
    @user = current_user
  end

end

app/views/dashboard/index.html.erb
<!-- app/views/dashboard/index.html.erb -->
<br>
<div class="card">
  <div class="card-body text-center">
    <h5 class="card-title text-center">Dead Man Switch Timer</h5>
      <% if current_user.dead_man_switch %>
        <h5>Your Dead Man Switch is set and will expire on <%= session[:formatted_date] %></h5>

        <button type="button" class="btn btn-success"><%= link_to "I'm Still Alive!", dead_man_switch_path(current_user), method: :patch, style: 'color:#FFFFFF;' %></br></button>
        <button type="button" class="btn btn-danger"><%= link_to "Cancel Dead Man Switch", dead_man_switch_path(current_user), method: :delete, style: 'color:#FFFFFF;'  %></button>

      <% else %>
        <h6 class="card-subtitle mb-2 text-muted text-center">You haven't set a timer yet. Click <%= link_to 'here', profile_path %> to visit your profile and set a timer now.</h6>
      <% end %>
  </div>
</div>