config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # Routes for Google authentication Login and Register
  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/about', to: 'about#index'

  resources :users, only: [:update, :edit]

  # Routes for a users extra information to be uploaded
  get '/extra_user_info_index/:id', to: 'extra_info#index', as: :extra_info
  get '/edit_extra_user_info/:id', to: 'extra_info#edit', as: :edit_extra_info
  put '/extra_user_info_edit/:id', to: 'extra_info#update', as: :update_info


  # User Profile Paths
  get '/profile', to: 'users#show', as: :profile
  get '/profile/edit', to: 'users#edit'
  patch '/profile/edit', to: 'users#update'
  namespace :profile do
    resources :contacts, only: [:new]
  end

  # Contact paths (also check contact paths namespaced in profile)
  resources :contacts, only: [:create]
  get '/contact_login', to: 'contact_login#edit'
  patch '/contact_login', to: 'contact_login#update'

  # GROUP do we want to namespace this?
  get '/dashboard', to: 'dashboard#index'

  # notification paths
  get '/notification', to: 'notification#message_sender'

  get '/report/:id', to: 'report#show', as: :report

  # dead_man_switch paths
  resources :dead_man_switch, only: [:create, :update, :destroy]

  #funeral arrangement path
  resources :users do
    resources :funerals, only: [:create, :new, :edit, :update]
  end

  # match '*path', to: 'application#four_oh_four', via: :all

end

app/models/user.rb
class User < ApplicationRecord

  # validations

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

  # relationships

  has_many :financial_accounts
  has_many :contacts
  has_one :dead_man_switch, dependent: :destroy
  has_one :employer
  has_one :funeral

  # Attachments

  has_many_attached :wills
  has_many_attached :powers_of_attorney
  has_many_attached :birth_certificates
  has_many_attached :finance_records
  has_many_attached :misc_files
  has_many_attached :va_benefits
  has_many_attached :employment_info
  has_many_attached :life_insurance
  has_many_attached :ss_info
  has_many_attached :tax_info
  has_many_attached :obituary
  has_many_attached :last_wishes
  has_many_attached :funeral_info
  has_many_attached :pet_info


  def find_primary_contact
    self.contacts.find_by(role: 1)
  end

  def progress
    counter = 0
    counter +=1 if wills.attachments != []
    counter +=1 if powers_of_attorney.attachments != []
    counter +=1 if birth_certificates.attachments != []
    counter +=1 if finance_records.attachments != []
    counter +=1 if misc_files.attachments != []
    counter +=1 if va_benefits.attachments != []
    counter +=1 if employment_info.attachments != []
    counter +=1 if life_insurance.attachments != []
    counter +=1 if ss_info.attachments != []
    counter +=1 if tax_info.attachments != []
    counter +=1 if obituary.attachments != []
    counter +=1 if last_wishes.attachments != []
    counter +=1 if funeral_info.attachments != []
    counter +=1 if pet_info.attachments != []
    ((counter.to_f / 14.0) * 100).round
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_reguser, except: [:new, :create]

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    flash[:success] = 'Your information has been successfully saved.'
    redirect_to profile_path
  end

  def show
    @user = current_user
    @funeral = @user.funeral
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :address, :organ_donor, :place_of_birth, :maiden_name)
  end
end

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->

<h1>Basic Information</h1>
<br>
<p>You can edit your basic information on this page.</p>
<br>
<%= form_for @user do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :address %>
  <%= f.text_area :address %>

  <%= f.submit 'Save' %>

<% end %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
    <br>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Dead Man Switch Timer</h5>
      <% if current_user.dead_man_switch %>
        <h6 class="card-subtitle mb-2 text-muted">You're all set for now. Your current timer will expire on <%= current_user.dead_man_switch.expires_at_in_time.strftime('%B %-d, %Y')%></h6>
        <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'>
                  Set or Reset Dead Man Switch Timer
                </button>
      <% else %>
        <h6 class="card-subtitle mb-2 text-muted">Click link below to add a timer</h6>
        <p>Add important files such as your will, power of attorney and any other documents with the link below. These files will be generated in the report for your primary contact.</p>
        <br>
        <div id="accordion">
          <div class="card">
            <div class="card-header">
              <h5 class="mb-0">
                <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'>
                  Set or Reset Dead Man Switch Timer
                </button>
              </h5>
            </div>
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body">
                <ul>
                  <div class="dead_man_switch_form">
                    <%= form_tag dead_man_switch_index_path, method: :post do  %>
                    <%= label_tag :dead_man_switch, "Timer Interval" %>
                    <%= number_field_tag 'quantity', nil, min: 1 %>
                    <%= select_tag :interval, options_for_select(intervals) %>
                    <%= submit_tag "Save" %>
                    <% end %>
                  </div>
                </ul>
              </div>
            </div>
          </div>
        </div>
    <% end% %>
  </div>
</div>

</br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Contacts</h5>
    <% if @user.contacts.empty? %>
    <h6 class="card-subtitle mb-2 text-muted">You haven't added any contacts yet.<br/>
    Add one using the link below and they'll be notified if your Dead Man Switch Timer expires.</h6>
    <% else %>
    <h6 class="card-subtitle mb-2 text-muted">Your primary contact is special</h6>
    <ul class="list-group list-group-flush">
      <% @user.contacts.each do |contact| %>
        <% if contact.role == 'primary' %>
            <li class="list-group-item"><span class="badge badge-primary">Primary</span>    <%= contact.first_name%> <%= contact.last_name %></li>
          <% else %>
            <li class="list-group-item"><span class="badge badge-secondary">Secondary</span>    <%= contact.first_name %> <%= contact.last_name %></li>
          <% end %>
      <% end %>
    </ul>
<br>
    <% end %>
    <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'><%= link_to 'Add A Contact', new_profile_contact_path %></button>
  </div>
</div>

<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Basic Information</h5>
    <h6 class="card-subtitle mb-2 text-muted">Here is your basic inormation</h6>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>First Name: </strong><%= @user.first_name%></li>
      <li class="list-group-item"><strong>Last Name: </strong><%= @user.last_name%></li>
      <li class="list-group-item"><strong>Email: </strong><%= @user.email%></li>
      <li class="list-group-item"><strong>Address: </strong><%= @user.address%></li>
    </ul>
<br>
    <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'><%= link_to 'Edit', edit_user_path(@user) %></button>
    
  </div>
</div>
<br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Additonal Information</h5>
    <h6 class="card-subtitle mb-2 text-muted">Will, Bank Accounts, Last Wishes, etc</h6>
    <p>Add important files such as your will, power of attorney and any other documents with the link below. These files will be generated in the report for your primary contact.</p>
    <br>


    <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'><%= link_to 'Edit Additional Information', extra_info_path(current_user) %></button>
  </div>
</div>

</br>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Funeral Arrangements<h5>
      <% if @user.funeral.nil? %>
        <h6 class="card-subtitle mb-2 text-muted">Add important files such as your will, power of attorney and any other documents with the link below. These files will be generated in the report for your primary contact.</h6>
        <br>
        <button type="button" class="btn btn-secondary"><%= link_to 'Add Funeral Arrangement', new_user_funeral_path(@user), style: 'color:#FFFFFF;' %></button>
      <% else %>
       <h6 class="card-subtitle mb-2 text-muted">Here is your current funeral inormation</h6>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Funeral Home: </strong><%= @user.funeral.funeral_home_name%></li>
      <li class="list-group-item"><strong>Phone: </strong><%= @user.funeral.funeral_home_phone%></li>
      <li class="list-group-item"><strong>Address: </strong><%= @user.funeral.funeral_home_address%></li>
    </ul>
    <br>
        <button class="btn btn-outline-primary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style='width'><%= link_to 'Update your Funeral Arrangement', edit_user_funeral_path(@user, @funeral) %></button>
      <% end %>
  </div>
</div>

<section>
  <ul class='update-profile list-group list-group-flush'>
    </br>
    <%= form_for(@user) do |f| %>
    <li class="list-group-item">
      <p>Organ Donor
        <%= f.radio_button :organ_donor, 'true' %>
        <%= f.label :organ_donor, 'Yes', :value => 'true' %>
        <%= f.radio_button :organ_donor, 'false' %>
        <%= f.label :organ_donor, 'No', :value => 'false' %>
      </p>
      <%= f.label :place_of_birth %>
      <%= f.text_field :place_of_birth %>
      </br>
      <%= f.label :maiden_name %>
      <%= f.text_field :maiden_name %>
      </br>
      <%= f.submit "Update" %>
      <% end %>
      </br>
    </ul>
  </section>
</section>