config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  # Routes for Google authentication Login and Register
  get 'auth/google_oauth2', to: 'auth#google_oauth'
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/about', to: 'about#index'

  resources :users, only: [:update, :edit]

  # Routes for a users extra information to be uploaded
  get '/extra_user_info_index/:id', to: 'extra_info#index', as: :extra_info
  get '/edit_extra_user_info/:id', to: 'extra_info#edit', as: :edit_extra_info
  put '/extra_user_info_edit/:id', to: 'extra_info#update', as: :update_info


  # User Profile Paths
  get '/profile', to: 'users#show', as: :profile
  get '/profile/edit', to: 'users#edit'
  patch '/profile/edit', to: 'users#update'
  namespace :profile do
    resources :contacts, only: [:new]
  end

  # Contact paths (also check contact paths namespaced in profile)
  resources :contacts, only: [:create]
  get '/contact_login', to: 'contact_login#edit'
  patch '/contact_login', to: 'contact_login#update'

  # GROUP do we want to namespace this?
  get '/dashboard', to: 'dashboard#index'

  # notification paths
  get '/notification', to: 'notification#message_sender'

  get '/report/:id', to: 'report#show', as: :report

  # dead_man_switch paths
  resources :dead_man_switch, only: [:create, :update, :destroy]

  #funeral arrangement path
  resources :users do
    resources :funerals, only: [:create, :new, :edit, :update]
  end

  # match '*path', to: 'application#four_oh_four', via: :all

end

app/views/layouts/_nav.html.erb
<!-- app/views/layouts/_nav.html.erb -->

<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
          <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto navbar-right">
    <% if current_user.nil? %>
      <li class="nav-item"><%= link_to 'Login', auth_google_oauth2_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Register', auth_google_oauth2_path, class: 'nav-link' %></li>
    <% else %>
      <% if current_user %>
      <li class="nav-item"><%= link_to 'Profile', profile_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'My Report', report_path(current_user), class: 'nav-link' %></li>
      <% end %>
      <li class="nav-item"><%= link_to 'Logout', logout_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <title>Coffin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>

    <div class="container" id="body-content-no-nav">
      <% flash.each do |flash_type, flash_message| %>
        <% if flash_message.class == Array %>
          <% flash_message.each do |single_message| %>
            <div class="alert alert-<%= flash_type %>" role="alert"><%= single_message %></div>
          <% end %>
        <% else %>
          <div class="alert alert-<%= flash_type %>" role="alert"><%= flash_message %></div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>